sudo: false
language: ruby
rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
before_install: gem install bundler --no-document
cache: bundler
script:
  - bundle exec rake spec
  - echo "gem 'hashie'" >> Gemfile
  - bundle
  - bundle exec rake spec_with_hashie
